import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";

pdfMake.vfs = pdfFonts.vfs;

const exportSalaryPDF = ({
    employee,
    salaries,
    totalSalary,
    paidSalary,
    pendingSalary,
    totalIncentive,
}) => {

    const documentDefinition = {

        pageSize: "A4",

        pageMargins: [40, 40, 40, 50],

        info: {
            title: "Employee Salary Report",
            author: "JobTrack CRM",
            subject: "Salary Report",
        },

        header: {
            margin: [40, 20, 40, 0],

            columns: [

                {
                    stack: [

                        {
                            text: "JobTrack CRM",
                            fontSize: 22,
                            bold: true,
                            color: "#059669",
                        },

                        {
                            text: "Employee Salary Report",
                            margin: [0, 4, 0, 0],
                            fontSize: 12,
                            color: "#64748b",
                        },

                    ],
                },

                {
                    alignment: "right",

                    text: `Generated : ${new Date().toLocaleDateString("en-IN")}`,

                    margin: [0, 8, 0, 0],

                    fontSize: 10,

                    color: "#64748b",
                },

            ],

        },

        footer: function (currentPage, pageCount) {

            return {

                margin: [40, 10],

                columns: [

                    {
                        text: "Generated by JobTrack CRM",
                        color: "#64748b",
                        fontSize: 9,
                    },

                    {
                        alignment: "right",

                        text: `Page ${currentPage} of ${pageCount}`,

                        color: "#64748b",

                        fontSize: 9,
                    },

                ],

            };

        },

        content: [

            {
                text: "Employee Information",

                style: "sectionTitle",

                margin: [0, 20, 0, 12],
            },

            {
                table: {

                    widths: ["30%", "*"],

                    body: [

                        ["Employee Name", employee.fullName],

                        ["Employee ID", employee.employeeId],

                        ["Department", employee.department],

                        ["Role", employee.role],

                    ],

                },

                layout: "lightHorizontalLines",

            },

            {
                text: "Salary Summary",

                style: "sectionTitle",

                margin: [0, 25, 0, 12],
            },

            {
                columns: [

                    {
                        width: "*",

                        table: {

                            body: [

                                [
                                    {
                                        text: "Total Salary",
                                        bold: true,
                                        fillColor: "#ECFDF5",
                                    },
                                    `Rs. ${totalSalary.toLocaleString("en-IN")}`,
                                ],

                            ],

                        },

                    },

                    {
                        width: 10,
                        text: "",
                    },

                    {
                        width: "*",

                        table: {

                            body: [

                                [
                                    {
                                        text: "Paid Salary",
                                        bold: true,
                                        fillColor: "#DBEAFE",
                                    },
                                    `Rs. ${paidSalary.toLocaleString("en-IN")}`,
                                ],

                            ],

                        },

                    },

                ],

            },

            {
                margin: [0, 10, 0, 0],

                columns: [

                    {
                        width: "*",

                        table: {

                            body: [

                                [
                                    {
                                        text: "Pending Salary",
                                        bold: true,
                                        fillColor: "#FEE2E2",
                                    },
                                    `Rs. ${pendingSalary.toLocaleString("en-IN")}`,
                                ],

                            ],

                        },

                    },

                    {
                        width: 10,
                        text: "",
                    },

                    {
                        width: "*",

                        table: {

                            body: [

                                [
                                    {
                                        text: "Total Incentive",
                                        bold: true,
                                        fillColor: "#FEF3C7",
                                    },
                                    `Rs. ${totalIncentive.toLocaleString("en-IN")}`,
                                ],

                            ],

                        },

                    },

                ],

            },
            {
                text: "Salary History",
                style: "sectionTitle",
                margin: [0, 30, 0, 12],
            },


            {
                table: {

                    headerRows: 1,

                    widths: [65, 55, 55, 55, 55, 65, 50],

                    body: [

                        [

                            {
                                text: "Month",
                                style: "tableHeader",
                            },

                            {
                                text: "Basic",
                                style: "tableHeader",
                            },

                            {
                                text: "Incentive",
                                style: "tableHeader",
                            },

                            {
                                text: "Paid",
                                style: "tableHeader",
                            },

                            {
                                text: "Pending",
                                style: "tableHeader",
                            },

                            {
                                text: "Net Salary",
                                style: "tableHeader",
                            },

                            {
                                text: "Status",
                                style: "tableHeader",
                            },


                        ],

                        ...salaries.map((salary) => [

                            `${salary.month} ${salary.year}`,

                            `Rs. ${Number(salary.basicSalary).toLocaleString("en-IN")}`,

                            `Rs. ${Number(salary.incentive).toLocaleString("en-IN")}`,

                            `Rs. ${Number(salary.paidAmount).toLocaleString("en-IN")}`,

                            `Rs. ${Number(salary.pendingAmount).toLocaleString("en-IN")}`,

                            `Rs. ${Number(salary.netSalary).toLocaleString("en-IN")}`,

                            {
                                text: salary.status,

                                bold: true,

                                color:
                                    salary.status === "Paid"
                                        ? "#16A34A"
                                        : salary.status === "Partial"
                                            ? "#D97706"
                                            : "#DC2626",

                            },
                          

                        ]),

                    ],

                },

                layout: {

                    fillColor: function (rowIndex) {

                        if (rowIndex === 0) return "#10B981";

                        return rowIndex % 2 === 0
                            ? "#F8FAFC"
                            : null;

                    },

                },

            },

            {
                text: "Remarks",
                style: "sectionTitle",
                margin: [0, 25, 0, 10],
            },

            ...salaries.map((salary) => ({
                margin: [0, 0, 0, 10],

                table: {
                    widths: [120, "*"],

                    body: [
                        [
                            {
                                text: `${salary.month} ${salary.year}`,
                                bold: true,
                                fillColor: "#F1F5F9",
                            },
                            salary.remark?.trim() || "No Remarks",
                        ],
                    ],
                },

                layout: "lightHorizontalLines",
            })),

        ],



        styles: {

            sectionTitle: {

                fontSize: 15,

                bold: true,

                color: "#0F172A",

            },

            tableHeader: {

                bold: true,

                color: "white",

                alignment: "center",

                margin: [0, 5, 0, 5],

            },

        },

    };

    pdfMake.createPdf(documentDefinition).download(
        `${employee.fullName}-Salary-Report.pdf`
    );

};

export default exportSalaryPDF;
